### ISSUE TITLE
They almost get zero profit because of taking action two

### ISSUE THREAD

**Issue by alanyuwenche** [sachink2010/AutomatedStockTrading-DeepQ-Learning#4]
Thanks for your great job and sharing.

I ran your code(aapl.us & amzn.us) and chose the models with good results(PnL). Then I used the same data(train data) to test the models. They almost get zero profit because of taking action two(do nothing). Do you have any idea about this problem?

**Comment by sachink2010** [comment]
hi Alanyuwenhe, Thanks for your positive feedback. I too am not an expert in this field, learning stuff.
I think the problem is happening because of the amount of price increase on Amazon and Google Stock during this period. If someone had bought these stocks 12-15 years back for say $1000 and Did Nothing, he/she would already have been multimillionaire. I tested my model on other stocks which were more stable (like GE) and it performed well.  So, may be better to train/test this kind of model on a more stable stock?
May be I am missing something in my model, do you have any suggestions to improve it?

**Comment by alanyuwenche** [comment]
Thank you very much for your quick response.

Your explanation seems reasonable. I would try the other stocks. Besides, I am quite curious about how you design the reward function. I knew you made some remarks in page 14 of project submission. But do you get these numbers by trial and error or by methodology?

Actually I solved the similar problem by trying different agent. If you are interested, please refer to the following link:
https://github.com/alanyuwenche/Reinforcement_Learning_for_Stock_Prediction
